### ISSUE TITLE
Refactor Audit-Scheduler for Enhanced Flexibility and Configuration

### ISSUE THREAD

**Issue by solaris007** [adobe/spacecat-audit-scheduler#47]
**Issue Description:**

The current audit-scheduler system is tightly coupled with AWS EventBridge, scheduling audits by type. This triggers a lambda function that calls the `/trigger` endpoint on the api-service, which then dispatches SQS messages according to the audit type and targeted sites.

With the requirement to support additional job types, including reporting and import tasks, we propose a simplified, configuration-driven architecture to improve flexibility and scalability.

**Proposed Changes:**

1. **Rename** `audit-scheduler` to `jobs-dispatcher` to reflect its broadened role.
2. **Introduce a Unified Configuration Schema**: This allows easy addition and management of different job types through a single configuration point.
3. **Simplify Scheduling**: Remove AWS EventBridge type-specific schedules in favor of generic schedules (`daily`, `weekly`, etc.), reducing complexity.
4. **Expand Queue Types**: Alongside the existing `audit-jobs` SQS queue, introduce `reporting-jobs` and `importer-jobs` queues to segregate tasks effectively.
5. **Implement Configuration-Based Dispatching**: The `jobs-dispatcher` will interpret the configuration to dispatch messages to the appropriate queues.

**Configuration Example:**
Jobs Configuration
```json
 {
       "daily": [
           { "group": "audits", "type": "lhs-mobile" },
           { "group": "audits", "type": "404" },
           { "group": "imports", "type": "rum-ingest" }
       ]
	"weekly": [
	   { "group": "reports", "type": "404-external-digest" },
	   { "group": "audits", "type": "apex" }
	]
}
```
Queue Configuration
```json
   {
         "audits": "sqs://.../spacecat-services-audit-jobs",
         "imports": "sqs://.../spacecat-services-import-jobs",
         "audits": "sqs://.../spacecat-services-audit-jobs",
}
```

**Operational Flow:**

- **Cron Trigger**: A generic signal initiates the flow, e.g., `{ "type": "weekly" }`.
- **Configuration Access**: The dispatcher reads the configuration to determine actions.
- **Task Dispatching**:
    - **Audits**: Filtered by interval, dispatch each audit task to `audit-jobs`.
    - **Imports**: Filter and dispatch import tasks to `importer-jobs`.
    - **Reports**: Filter and dispatch reporting tasks to `reporting-jobs`.

Each dispatch includes a payload specifying the task type and interval, ensuring tasks are queued appropriately.

**Operational Flow with Event Payload Examples:**

Upon receiving a cron trigger with a payload indicating the interval, e.g., `{ "type": "weekly" }`, the `jobs-dispatcher` will:

1. **Access the Unified Configuration** to determine the tasks to be executed based on the specified interval.

2. **Dispatch Tasks Accordingly**:

   - **Audits**:
     - Filter audits by the specified interval.
     - For each matching audit, dispatch a message to the `audit-jobs` queue.
     - **Example Payload for Audit-Jobs Queue**:
       ```json
       {
         "type": "lhs-mobile",
         "interval": "daily"
       }
       ```
       ```json
       {
         "type": "404",
         "interval": "weekly"
       }
       ```

   - **Imports**:
     - Filter imports by the specified interval.
     - For each matching import task, dispatch a message to the `importer-jobs` queue.
     - **Example Payload for Importer-Jobs Queue**:
       ```json
       {
         "type": "rum-ingest",
         "interval": "daily"
       }
       ```

   - **Reports**:
     - Filter reports by the specified interval.
     - For each matching report, dispatch a message to the `reporting-jobs` queue.
     - **Example Payload for Reporting-Jobs Queue**:
       ```json
       {
         "type": "404-external-digest",
         "interval": "weekly"
       }
       ```
       ```json
       {
         "type": "apex",
         "interval": "weekly"
       }
       ```

These payload examples illustrate the structure and information each dispatched message will contain, ensuring that each job type is processed according to its specific requirements and scheduling configuration.

**Comment by ekremney** [comment]
A flat job configuration would be easier to configure and manage:

```js
 [
   { 
     "group": "audits", 
     "type": "lhs-mobile", 
     "interval": "daily" 
   }, { 
     "group": "audits", 
     "type": "404", 
     "interval": "daily" 
   }, { 
     "group": "imports", 
     "type": "rum-ingest", 
     "interval": "daily" 
   }, { 
     "group": "reports", 
     "type": "404-external-digest", 
     "interval": "weekly" 
   }, { 
     "group": "audits", 
     "type": "apex", 
     "interval": "weekly" 
     }
]
```

**Comment by ekremney** [comment]
Overall, everything looks good. But I have two more things to mention:

1. It's not very clear what 'weekly' and 'daily' mean in practical terms. Could you explain a bit more? For example, does a 'weekly' task happen once every week, like on sunday at midnight?

2. Wouldn't it be too much stress to schedule all the jobs at the same time? Imagine if we have 10 weekly and 10 daily jobs. If they all start together, it could overload downstream components

**Comment by alinarublea** [comment]
The Spacecat lucidchart is now updated with the flat structure for the jobs configurations.
1. Yes, your understanding is correct weekly means once every week on a specific weekdayday(ex: sunday) and hour (ex: midnight)
2. I think it won t overload much the workers because they process the jobs sequentially and for now we don t have a time restrictions for the jobs to finish executing. We can see in practice the effect and adjust accordingly.
